version: '3'
services:
  localstack:
    container_name: localstack
    image: localstack/localstack

    ports:
      - "4584:4584"

    environment:
      - DEFAULT_REGION=eu-central-1
      - SERVICES=secretsmanager

    networks:
      - internal

  app:
    container_name: app
    build: ./app

    ports:
      - "3000:3000"

    environment:
      - AWS_REGION=eu-central-1
      - AWS_ACCESS_KEY_ID=keyid
      - AWS_SECRET_ACCESS_KEY=secretkey
      - AWS_SESSION_TOKEN=token

    depends_on:
      - localstack

    networks:
      - internal
      - web

networks:
  internal:
    internal: true
  web:
